Repository magma/domain-proxy, pull requests merged in 2021-06, with the labels that each got.

#91 remove skaffold.yml repetition
  skaffold.yaml
Labels: size/L

#94 change memory allocation to minikube instance
  .github/workflows/e2e-tests.yml
  .github/workflows/helm-chart-tests.yml
  .github/workflows/integration-tests.yml
Labels: size/M

#97 fix integration tests from skaffold
  .github/workflows/codecov.yml
  skaffold.yaml
Labels: size/M

#102 Remove unnecessary integration tests
  .github/workflows/e2e-tests.yml
  .github/workflows/helm-chart-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/publish-integration-tests-results.yml
  Makefile
  skaffold.yaml
  tools/deployment/tests/configuration_controller_test_deployment.yml
  tools/deployment/tests/radio_controller_test_deployment.yml
Labels: size/L

#103 Fixed PC response checking and GRPC return value
  protocol_controller/grpc_communication/get_common_rc_response.py
Labels: size/S

#96 Horizontal Pod Autoscaling
  .github/workflows/configuration-controller.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/helm-chart-tests.yml
  .github/workflows/integration-tests.yml
  Makefile
  charts/domain-proxy/README.md
  charts/domain-proxy/examples/minikube_values.yml
  charts/domain-proxy/values.yaml
  skaffold.yaml
Labels: size/L

#108 Added grant storing
  Makefile
  configuration_controller/request_consumer/request_db_consumer.py
  configuration_controller/response_processor/response_db_processor.py
  configuration_controller/response_processor/strategies/map_keys_generation.py
  configuration_controller/response_processor/strategies/response_processing.py
  configuration_controller/response_processor/strategies/strategies_mapping.py
  configuration_controller/run.py
  configuration_controller/tests/fixtures/fake_requests/spectrum_inquiry_requests.py
  configuration_controller/tests/unit/test_request_consumer.py
  configuration_controller/tests/unit/test_request_formatting.py
  configuration_controller/tests/unit/test_response_processor.py
  db_service/db_initialize.py
  db_service/migrations/env.py
  db_service/migrations/versions/4a706d0adc45_initial_revision.py
  db_service/migrations/versions/9fb9db0b2bcc_.py
  db_service/models.py
  db_service/session_manager.py
  db_service/tests/unit/test_db_initialization.py
  mappings/types.py
  protocol_controller/grpc_communication/get_common_rc_response.py
  protocol_controller/tests/unit/test_sas_interface.py
  radio_controller/run.py
  radio_controller/service.py
  radio_controller/tests/unit/test_radio_controller_service.py
Labels: size/XL

#114 update helm chart
  Makefile
  charts/domain-proxy/README.md
  charts/domain-proxy/examples/minikube_values.yml
  charts/domain-proxy/templates/configuration_controller/ca.yml
  charts/domain-proxy/templates/configuration_controller/deployment.yml
  charts/domain-proxy/templates/configuration_controller/sas_certs_secret.yml
  charts/domain-proxy/templates/configuration_controller/sas_keys_secret.yml
  charts/domain-proxy/templates/configuration_controller/tls.yml
  charts/domain-proxy/values.yaml
  configuration_controller/config.py
  skaffold.yaml
  tools/deployment/tests/protocol_controller_test_deployment.yml
Labels: size/L
