Repository magma/domain-proxy, pull requests merged in 2021-04, with the labels that each got.

#27 Request merging
  configuration_controller/request_formatting/__init__.py
  configuration_controller/request_formatting/exceptions.py
  configuration_controller/request_formatting/merger.py
  configuration_controller/tests/__init__.py
  configuration_controller/tests/fixtures/fake_request_queues/mixed_queued_requests.json
  configuration_controller/tests/fixtures/fake_request_queues/queued_requests.json
  configuration_controller/tests/fixtures/fake_request_queues/queued_requests_with_one_cumulative_request.json
  configuration_controller/tests/requirements.txt
  configuration_controller/tests/unit/__init__.py
  configuration_controller/tests/unit/test_request_formatting.py
Labels: size/XS

#28 Fixed path to fixtures in unit tests
  configuration_controller/request_formatting/merger.py
  configuration_controller/tests/requirements.txt
  configuration_controller/tests/unit/test_request_formatting.py
Labels: size/XS

#34 Configuration controller CI
  .github/workflows/configuration_controller_build.yml
  .github/workflows/configuration_controller_release.yml
  .github/workflows/configuration_controller_tag_latest.yml
  skaffold.yaml
Labels: size/L

#35 fix for tagging docker images
  .github/workflows/configuration_controller_build.yml
  .github/workflows/configuration_controller_release.yml
  .github/workflows/configuration_controller_tag_latest.yml
Labels: size/XS

#36 Simplify request merger
  configuration_controller/request_formatting/exceptions.py
  configuration_controller/request_formatting/merger.py
  configuration_controller/tests/unit/fixtures/fake_request_queues/mixed_queued_requests.py
  configuration_controller/tests/unit/fixtures/fake_request_queues/queued_requests.py
  configuration_controller/tests/unit/fixtures/fake_request_queues/queued_requests_with_one_cumulative_request.py
  configuration_controller/tests/unit/test_request_formatting.py
Labels: size/L

#38 RabbitMQ deployment manifests
  skaffold.yaml
  tools/deployment/rabbitmq_cluster_definition.yaml
  tools/deployment/rabbitmq_secrets.yaml
Labels: size/S

#47 change depend job name
  .github/workflows/configuration_controller.yml
Labels: size/XS

#48 [WIP] integration tests
  .github/workflows/configuration_controller.yml
  Makefile
  configuration_controller/.dockerignore
  configuration_controller/Dockerfile
  skaffold.yaml
  tools/deployment/tests/configuration_controller_deployment.yaml
  tools/deployment/vendor/fake_sas.yml
  tools/deployment/vendor/rabbitmq_cluster_definition.yaml
Labels: size/L

#50 Create separate step for unit tests
  .github/workflows/configuration-controller.yml
  .github/workflows/integration-tests.yml
  .github/workflows/publish-junit.yml
  Makefile
  tools/deployment/tests/configuration_controller_test_deployment.yml
Labels: size/L

#52 fix-makefile-default-shell
  Makefile
Labels: size/XS

#56 Add integration tests to ssl-verification
  configuration_controller/request_router/request_router.py
  configuration_controller/tests/integration/test_configuration_controller.py
Labels: size/M
